pull_request_rules:
  - name: Automatic merge on approval for Dependabot
    conditions:
      - author=dependabot[bot]
      - check-success=build
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
